version: "3.5"
services:
  nginx:
    build:
      context: ./docker/dev/nginx
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/dev/php-fpm
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 remote_connect_back=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: andrgladkikh
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: andrgladkikh
    ports:
      - "5432:5432"
volumes:
  postgres: